update
QuasarApp/Qt-Secret pull request #105
Opened 2023-03-17 06:48 UTC by paipeng

2023-03-17 06:48 UTC, paipeng commented
update

2023-03-17 07:51 UTC, EndrII requested changes
Thank you for your work. But these changes need to be improved.

2023-03-17 07:51 UTC, EndrII commented on src/Qt-RSA/qrsaencryption.h
> +        Auto2 = 2
This is bad name of mode. Please add a readable description for this mode and rename it.

2023-03-17 07:51 UTC, EndrII commented on src/Qt-RSA/qrsaencryption.cpp
> +        blockSizeIn = getBlockSize(m) + 1;
For what you use signing block with oversize ?

2023-03-17 07:51 UTC, EndrII commented on src/Qt-RSA/qrsaencryption.cpp
> +    QString digestOIDHexString ="3031300d060960864801650304020105000420";
Please add full description about this magic number ...

2023-03-17 07:51 UTC, EndrII commented on src/Qt-RSA/qrsaencryption.cpp
> +    QString paddedHexString ="0001ffffffffffffffffffff00";
add description

2023-03-17 07:51 UTC, EndrII commented on src/Qt-RSA/qrsaencryption.cpp
> +    return signature;
I still no understand what you sign? 
you have a raw data that want to sign, but you sign them with magic arrays. 
please attach full description of this function.

2023-03-17 07:51 UTC, EndrII commented on src/Qt-RSA/qrsaencryption.cpp
> +    auto signStartPos = 19+ 13;
Why sign raker began of this 19 + 13.
Please describe your code. 

If you want to found a beginning of your sign, use hooks (or magic symbol, you need to find it on array before processing).

Or use constant variables with readable names.

2023-03-17 07:51 UTC, EndrII commented on src/Qt-RSA/qrsaencryption.cpp
> +#if 0
Or remove it or add useful condition.

2023-03-17 07:51 UTC, EndrII commented on src/Qt-RSA/qrsaencryption.h
> +    bool checkSignMessageJava(const QByteArray &message, const QByteArray &rawData, const QByteArray &pubKey, const BlockSize blockSizeMode = BlockSize::OneByte);
Add XML description for all new methods

2023-03-17 07:52 UTC, EndrII commented
so rename please pull request.

2023-11-03 18:33 UTC, EndrII commented
Unfortunately. But I drop support of this library. See my new library for works with RSA and ECDSA.  [easyssl](https://github.com/QuasarApp/easyssl)

2023-11-03 18:33 UTC, closed without merging